# Generated by Django 4.1.2 on 2022-10-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='media/images/no-profile-image.jfif', upload_to='images/'),
        ),
    ]
