# Generated by Django 4.1.2 on 2022-10-29 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0009_articlecomment_data_created_articlecomment_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='users_which_liked_comment',
            field=models.ManyToManyField(blank=True, related_name='user_lied_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postarticle',
            name='users_which_liked_article',
            field=models.ManyToManyField(blank=True, related_name='user_lied_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
