# Generated by Django 4.1.2 on 2022-10-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_articlecomment_users_which_liked_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='postarticle',
            name='likes',
        ),
    ]
